name: Build Kernel Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential linux-headers-$(uname -r)

      - name: Build hello module
        working-directory: ./hello
        run: |
          make
          ls -lh *.ko || echo "hello module failed to build."

      - name: Build simple module
        working-directory: ./simple
        run: |
          make
          ls -lh *.ko || echo "simple module failed to build."
