name: Build Kernel Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential linux-headers-$(uname -r)

      - name: Build kernel module
        run: make

      - name: Show build results
        run: ls -lh *.ko || echo "Build failed"
